name: Generate RSS Feed

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install jsdom

      - name: Generate RSS Feed
        run: node generate-rss.js

      - name: Commit & Push RSS
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "🤖 Update RSS feed" || echo "No changes to commit"
          git push
